export const tools = [
  {
    name: "Minea",
    url: "https://minea.com",
    icon: "https://logo.clearbit.com/minea.com",
    description: "All-in-one product research tool for dropshipping...",
  },
  {
    name: "WinningHunter",
    url: "https://winninghunter.com",
    icon: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSlRQdG5BNioQ707VLYYFQIa_HdGTOfyNJFXQ&s",
    description: "Discover trending products for your store...",
  },
  {
    name: "Adspy",
    url: "https://www.adspy.com",
    icon: "https://logo.clearbit.com/adspy.com",
    description: "Spy on competitors' ad strategies fast...",
  },
  {
    name: "Canva Pro",
    url: "https://www.canva.com",
    icon: "https://logo.clearbit.com/canva.com",
    description: "Design anything with this online platform...",
  },
  {
    name: "ChatGPT Plus",
    url: "https://chat.openai.com",
    icon: "https://logo.clearbit.com/openai.com",
    description: "Chat with GPT-4 on OpenAI platform...",
  },
  {
    name: "Adscalp",
    url: "https://adscalp.com",
    icon: "https://cdn.brandfetch.io/idRoLQuHnV/w/150/h/180/theme/dark/logo.png?c=1bxid64Mup7aczewSAYMX&t=1743283725442",
    description: "AI-powered tool for marketers and ads...",
  },
  {
    name: "Adsparo",
    url: "https://adsparo.com",
    icon: "https://cdn.brandfetch.io/id1asLzjwB/w/400/h/400/theme/dark/icon.jpeg?c=1bxid64Mup7aczewSAYMX&t=1748369873662",
    description: "Platform to optimize and scale ads...",
  },

  {
    name: "Adworld Prime",
    url: "https://adworldconference.com",
    icon: "https://logo.clearbit.com/adworldconference.com",
    description: "Conference for advertisers and marketers...",
  },
  {
    name: "AliShark",
    url: "https://alishark.com",
    icon: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTroN6Nx1ok2UVXYIoLd3ZiAQtps8GBEWM9gA&s",
    description: "Analyze winning products for dropshipping...",
  },
  {
    name: "Anyword",
    url: "https://anyword.com",
    icon: "https://logo.clearbit.com/anyword.com",
    description: "Write better marketing content using AI...",
  },
  {
    name: "BigSpy",
    url: "https://bigspy.com",
    icon: "https://logo.clearbit.com/bigspy.com",
    description: "Ad intelligence tool for brands growth...",
  },
  {
    name: "Brain.fm",
    url: "https://www.brain.fm",
    icon: "https://logo.clearbit.com/brain.fm",
    description: "Boost focus with science-backed music...",
  },

  {
    name: "Captions.ai",
    url: "https://captions.ai",
    icon: "https://logo.clearbit.com/captions.ai",
    description: "AI captions generator for social content...",
  },

  {
    name: "Chatsonic",
    url: "https://writesonic.com/chat",
    icon: "https://logo.clearbit.com/writesonic.com",
    description: "AI-powered writing assistant for content...",
  },
  {
    name: "Copy.ai",
    url: "https://www.copy.ai",
    icon: "https://logo.clearbit.com/copy.ai",
    description: "Copywriting tool powered by artificial intelligence...",
  },
  {
    name: "CreativeOS",
    url: "https://creativeos.co",
    icon: "https://logo.clearbit.com/creativeos.co",
    description: "Workspace to manage creative workflows easily...",
  },
  {
    name: "Denote",
    url: "https://denote.app",
    icon: "https://cdn.brandfetch.io/idh__5COCU/w/300/h/300/theme/dark/icon.png?c=1bxid64Mup7aczewSAYMX&t=1739015637853",
    description: "Simple note-taking tool for busy teams...",
  },
  {
    name: "DesignBeast",
    url: "https://designbeast.io",
    icon: "https://logo.clearbit.com/designbeast.io",
    description: "Create amazing designs and animation easily...",
  },
  {
    name: "Dropispy",
    url: "https://dropispy.com",
    icon: "https://logo.clearbit.com/dropispy.com",
    description: "Spy on winning dropshipping products quickly...",
  },
  {
    name: "Durable",
    url: "https://durable.co",
    icon: "https://logo.clearbit.com/durable.co",
    description: "AI website builder for small businesses...",
  },
  {
    name: "Ecomhunt",
    url: "https://ecomhunt.com",
    icon: "https://logo.clearbit.com/ecomhunt.com",
    description: "Find trending products to sell online...",
  },
  {
    name: "Foreplay",
    url: "https://www.foreplay.co",
    icon: "https://logo.clearbit.com/foreplay.co",
    description: "Creative platform for marketers and creators...",
  },
  {
    name: "Frase",
    url: "https://www.frase.io",
    icon: "https://logo.clearbit.com/frase.io",
    description: "AI-powered content writing for SEO teams...",
  },
  {
    name: "Freepik",
    url: "https://www.freepik.com",
    icon: "https://logo.clearbit.com/freepik.com",
    description: "Free resource for icons, images and more...",
  },
  {
    name: "Futurelib",
    url: "https://futuretools.io/tools/futurelib",
    icon: "https://logo.clearbit.com/futuretools.io",
    description: "Curated library of AI tools and utilities...",
  },
  {
    name: "GetHookd",
    url: "https://www.gethookd.com",
    icon: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQwIm3YWuaigHk2lphHl8OLIg3vFtVA6bSNgcsSJ-S7liWpp-w15u8IWWvC5vHDu0P1P-I&usqp=CAU",
    description: "Get feedback on your designs fast...",
  },
  {
    name: "Hailuo AI",
    url: "https://www.hailuoai.com",
    icon: "https://logo.clearbit.com/hailuoai.com",
    description: "AI chatbot assistant for daily productivity...",
  },
  {
    name: "HeyGen",
    url: "https://www.heygen.com",
    icon: "https://logo.clearbit.com/heygen.com",
    description: "Generate videos with lifelike avatars quickly...",
  },
  {
    name: "Jasper",
    url: "https://www.jasper.ai",
    icon: "https://logo.clearbit.com/jasper.ai",
    description: "Write smarter and faster using this AI...",
  },
  {
    name: "Jitter",
    url: "https://jitter.video",
    icon: "https://logo.clearbit.com/jitter.video",
    description: "Motion design and animation tool online...",
  },
  {
    name: "Krea AI",
    url: "https://www.krea.ai",
    icon: "https://logo.clearbit.com/krea.ai",
    description: "Create art and visuals with AI tools...",
  },
  {
    name: "Mediamodifier",
    url: "https://mediamodifier.com",
    icon: "https://logo.clearbit.com/mediamodifier.com",
    description: "Mockups and design templates made easy...",
  },
  {
    name: "Midjourney",
    url: "https://www.midjourney.com",
    icon: "https://logo.clearbit.com/midjourney.com",
    description: "AI art generator from simple prompts...",
  },
];
